---
# -------------------
# Dexined (edge detector)
# -------------------

- model_id: "hinters-dexined"
  model: "halffried/gyre_hinters"
  subfolder: "dexined"
  type: "module"
  class: "DexiNed(pretrained=False)"

- id: "hinters-dexined"
  task: "edge_detection"
  default: True
  class: "DexinedPipeline"
  model: "@empty"
  overrides:
    module: "@hinters-dexined"

# -------------------
# Linedrawing - these are all "edge detection" as far as Gyre is concerned, although
# results will vary a lot if you use the wrong one for the wrong hint prompt handler
# -------------------

- model_id: "hinters-lineart-anime"
  model: "halffried/gyre_hinters"
  subfolder: "lineart_anime"
  type: "module"
  class: DrawingGenerator(input_nc=3, output_nc=1, n_residual_blocks=3)

- id: "hinters-lineart-anime"
  task: "edge_detection"
  class: InformativeDrawingPipeline
  model: "@hinters-lineart-anime"

- model_id: "hinters-lineart-contour"
  model: "halffried/gyre_hinters"
  subfolder: "lineart_contour"
  type: "module"
  class: DrawingGenerator(input_nc=3, output_nc=1, n_residual_blocks=3)

- id: "hinters-lineart-contour"
  task: "edge_detection"
  class: InformativeDrawingPipeline
  model: "@hinters-lineart-contour"

- model_id: "hinters-lineart-opensketch"
  model: "halffried/gyre_hinters"
  subfolder: "lineart_opensketch"
  type: "module"
  class: DrawingGenerator(input_nc=3, output_nc=1, n_residual_blocks=3)

- id: "hinters-lineart-opensketch"
  task: "edge_detection"
  class: InformativeDrawingPipeline
  model: "@hinters-lineart-opensketch"

# -------------------
# Uniformer (segmenter)
# -------------------

- model_id: "hinters-uniformer-base"
  model: "halffried/gyre_hinters"
  subfolder: "uniformer_base"
  type: "module"
  class: MmLoader/load_mmseg

- model_id: "hinters-uniformer-small"
  model: "halffried/gyre_hinters"
  subfolder: "uniformer_small"
  type: "module"
  class: MmLoader/load_mmseg

- id: "hinters-uniformer"
  task: "segmentation"
  default: True
  class: "MmsegPipeline"
  model: "@empty"
  overrides:
    module: "@hinters-uniformer-small"

# -------------------
# Mmdet / Mmpose (pose estimator)
# -------------------

- model_id: "hinters-keypose-detector-r50"
  model: "halffried/gyre_hinters"
  subfolder: "keypose_mmdet_fasterrcnn_r50"
  type: "module"
  class: MmLoader/load_mmdet

- model_id: "hinters-keypose-detector-x101"
  model: "halffried/gyre_hinters"
  subfolder: "keypose_mmdet_fasterrcnn_x101"
  type: "module"
  class: MmLoader/load_mmdet

- model_id: "hinters-keypose-posemodel"
  model: "halffried/gyre_hinters"
  subfolder: "keypose_mmpose_hrnet"
  type: "module"
  class: MmLoader/load_mmpose

- model_id: "hinters-keypose-posemodel-384"
  model: "halffried/gyre_hinters"
  subfolder: "keypose_mmpose_hrnet_384"
  type: "module"
  class: MmLoader/load_mmpose

- id: "hinters-pose"
  task: "pose"
  default: True
  class: "MmposePipeline"
  model: "@empty"
  overrides:
    detector: "@hinters-keypose-detector-x101"
    posemodel: "@hinters-keypose-posemodel-384"

# -------------------
# InSPyReNet (background remover)
# -------------------

- model_id: "inspyrenet"
  model: "halffried/gyre_hinters"
  subfolder: "inspyrenet_base"
  type: "module"
  fp16: "prevent"
  # Config from https://github.com/plemeri/transparent-background/blob/main/transparent_background/Remover.py#L26
  class: "InSPyReNet_SwinB(depth=64, pretrained=False, base_size=[1024, 1024], threshold=None)"

- model_id: "inspyrenet-fast"
  model: "halffried/gyre_hinters"
  subfolder: "inspyrenet_fast"
  type: "module"
  fp16: "prevent"
  # Config from https://github.com/plemeri/transparent-background/blob/main/transparent_background/Remover.py#L32
  class: "InSPyReNet_SwinB(depth=64, pretrained=False, base_size=[384, 384], threshold=512)"

- id: "inspyrenet"
  task: "background-removal"
  default: True
  class: InSPyReNetPipeline
  model: "@empty"
  overrides:
    module: "@inspyrenet"

# -------------------
# Normal/bae
# -------------------

- model_id: "hinters-baenormal"
  model: "halffried/gyre_hinters"
  subfolder: "baenormal"
  type: "module"
  class: BaenormalLoader/load

- id: "hinters-baenormal"
  task: "normal"
  default: True
  class: BaenormalPipeline
  model: "@hinters-baenormal"
