# Two different VAEs from stability

- model_id: "stability-vae-ema"
  type: "vae"
  model: "stabilityai/sd-vae-ft-ema"
  local_model: "./sd-vae-ft-ema"

- model_id: "stability-vae-mse"
  type: "vae"
  model: "stabilityai/sd-vae-ft-mse"
  local_model: "./sd-vae-ft-mse"

- model_id: "waifu-vae-anime"
  type: "ckpt/v1-inference"
  model: "hakurei/waifu-diffusion-v1-4"
  subfolder: "vae"
  allow_patterns: "kl-f8-anime.ckpt"
  whitelist: ["vae"]
  fp16: "prevent"

- model_id: "waifu-vae-anime2"
  type: "ckpt/v1-inference"
  model: "hakurei/waifu-diffusion-v1-4"
  subfolder: "vae"
  allow_patterns: "kl-f8-anime2.ckpt"
  whitelist: ["vae"]
  fp16: "prevent"
