# Depth estimation engines

# This is a bit different to the previous engines. It's a task: "depth" engine.
# That means, instead of generating images based on prompts, it generates depth_maps
# from images. Generally, we want to keep these engines for internal use only, which
# is why it's not marked as visible
- id: "depth-midas-beit-large-512"
  enabled: False
  task: "depth"
  model: "@midas-beit-large-512"

- id: "depth-midas-swin2-large-384"
  enabled: False
  task: "depth"
  model: "@midas-swin2-large-384"

- id: "depth-midas-nextvit-large-384"
  enabled: False
  task: "depth"
  model: "@midas-nextvit-large-384"

- id: "depth-zoe-n"
  default: True
  task: "depth"
  model: "@zoe-n"
  class: "ZoeDepthPipeline"

- id: "depth-zoe-k"
  enabled: False
  task: "depth"
  model: "@zoe-k"
  class: "ZoeDepthPipeline"

- id: "depth-zoe-nk"
  enabled: False
  task: "depth"
  model: "@zoe-nk"
  class: "ZoeDepthPipeline"

- id: "depth-stable-diffusion-v2-depth"
  enabled: False
  task: "depth"
  class: "DiffusersDepthPipeline"
  model: "@depth-stable-diffusion-v2-depth"
