- hintset_id: "hintset-sd15-t2i"
  t2i/canny:
    aliases: "canny"
    model: "@t2i-adapter-canny"
  t2i/color:
    aliases: "color"
    model: "@t2i-adapter-color"
  t2i/depth:
    aliases: "depth"
    model: "@t2i-adapter-depth"
  t2i/keypose:
    aliases: ["keypose", "pose/keypose"]
    model: "@t2i-adapter-keypose"
  t2i/openpose:
    aliases: ["pose", "openpose", "pose/openpose"]
    model: "@t2i-adapter-openpose"
  t2i/seg:
    aliases: ["segmentation", "segmentation/coco"]
    model: "@t2i-adapter-seg"
  t2i/sketch:
    aliases: ["sketch", "scribble"]
    model: "@t2i-adapter-sketch"
  t2i/style:
    aliases: "style"
    model: "@t2i-adapter-style"
  t2i/zoedepth:
    aliases: ["depth", "depth/zoe"]
    priority: 25
    model: "@t2i-adapter-zoedepth"

- hintset_id: "hintset-sd15-coadapter"
  coadapter/canny:
    aliases: "canny"
    model: "@coadapter-canny"
  coadapter/color:
    aliases: "color"
    model: "@coadapter-color"
  coadapter/depth:
    aliases: "depth"
    model: "@coadapter-depth"
  coadapter/sketch:
    aliases: ["sketch", "scribble"]
    model: "@coadapter-sketch"
  coadapter/style:
    aliases: "style"
    model: "@coadapter-style"

- hintset_id: "hintset-sd15-controlnet"
  controlnet/canny:
    aliases: "canny"
    priority: 200
    model: "@controlnet-canny"
  controlnet/depth:
    aliases: "depth"
    priority: 50
    model: "@controlnet-depth"
  controlnet/hed:
    aliases: ["hed", "softedge"]
    model: "@controlnet-hed"
  controlnet/mlsd:
    aliases: "mlsd"
    model: "@controlnet-mlsd"
  controlnet/normal:
    aliases: "normal"
    model: "@controlnet-normal"
  controlnet/openpose:
    aliases: ["pose", "openpose", "pose/openpose"]
    model: "@controlnet-openpose"
    priority: 200
  controlnet/scribble:
    aliases: ["sketch", "scribble"]
    priority: 50
    model: "@controlnet-scribble"
  controlnet/seg:
    aliases: ["segmentation", "segmentation/ade20k"]
    model: "@controlnet-seg"

- hintset_id: "hintset-sd15-controlnet11"
  controlnet11/canny:
    aliases: "canny"
    model: "@controlnet11-canny"
    priority: 300
  controlnet11/depth:
    aliases: ["depth", "depth/zoe"]
    model: "@controlnet11-depth"
    priority: 75
  controlnet11/inpaint:
    aliases: "inpaint"
    model: "@controlnet11-inpaint"
  controlnet11/pix2pix:
    aliases: "pix2pix"
    model: "@controlnet11-pix2pix"
  controlnet11/lineart:
    aliases: "lineart"
    model: "@controlnet11-lineart"
  controlnet11/lineart-anime:
    aliases: ["lineart", "lineart/anime"]
    model: "@controlnet11-lineart-anime"
  controlnet11/mlsd:
    aliases: "mlsd"
    model: "@controlnet11-mlsd"
    priority: 200
  controlnet11/normalbae:
    aliases: ["normal", "normal/bae"]
    model: "@controlnet11-normalbae"
    priority: 200
  controlnet11/openpose:
    aliases: ["pose", "openpose", "pose/openpose"]
    model: "@controlnet11-openpose"
    priority: 200
  controlnet11/scribble:
    aliases: ["sketch", "scribble"]
    model: "@controlnet11-scribble"
    priority: 75
  controlnet11/seg:
    aliases: ["segmentation", "segmentation/ade20k"]
    model: "@controlnet11-seg"
  controlnet11/shuffle:
    aliases: "style"
    model: "@controlnet11-shuffle"
    priority: 50
  controlnet11/softedge:
    aliases: ["hed", "softedge"]
    model: "@controlnet11-softedge"
    priority: 200

- hintset_id: "hintset-sd15-common"
  "@hintset-sd15-coadapter": "*"
  "@hintset-sd15-t2i":
    - "t2i/keypose"
    - "t2i/openpose"
  "@hintset-sd15-controlnet11":
    - "controlnet11/canny"
    - "controlnet11/normalbae"
    - "controlnet11/seg"
    - "controlnet11/shuffle"
    - "controlnet11/softedge"

- hintset_id: "hintset-sd15-complete"
  "@hintset-sd15-coadapter": "*"
  "@hintset-sd15-t2i": "*"
  "@hintset-sd15-controlnet": "*"
