- hintset_id: "hintset-sd15-t2i"
  t2i/canny:
    aliases: "canny"
    model: "@t2i-adapter-canny"
  t2i/color:
    aliases: "color"
    model: "@t2i-adapter-color"
  t2i/depth:
    aliases: "depth"
    model: "@t2i-adapter-depth"
  t2i/keypose:
    aliases: ["keypose", "pose/keypose"]
    model: "@t2i-adapter-keypose"
  t2i/openpose:
    aliases: ["pose", "openpose", "pose/openpose"]
    model: "@t2i-adapter-openpose"
  t2i/seg:
    aliases: ["segmentation", "segmentation/coco"]
    model: "@t2i-adapter-seg"
  t2i/sketch:
    aliases: ["sketch", "scribble"]
    model: "@t2i-adapter-sketch"
  t2i/style:
    aliases: "style"
    model: "@t2i-adapter-style"
  t2i/zoedepth:
    aliases: ["depth", "depth/zoe"]
    priority: 25
    model: "@t2i-adapter-zoedepth"

- hintset_id: "hintset-sd15-coadapter"
  coadapter/canny:
    aliases: "canny"
    model: "@coadapter-canny"
  coadapter/color:
    aliases: "color"
    model: "@coadapter-color"
  coadapter/depth:
    aliases: "depth"
    model: "@coadapter-depth"
  coadapter/sketch:
    aliases: ["sketch", "scribble"]
    model: "@coadapter-sketch"
  coadapter/style:
    aliases: "style"
    model: "@coadapter-style"

- hintset_id: "hintset-sd15-controlnet10"
  controlnet10/canny:
    aliases: ["controlnet/canny", "canny"]
    priority: 200
    model: "@controlnet-canny"
  controlnet10/depth:
    aliases: ["controlnet/depth", "depth"]
    priority: 50
    model: "@controlnet-depth"
  controlnet10/hed:
    aliases: ["controlnet/hed", "hed"]
    model: "@controlnet-hed"
  controlnet10/mlsd:
    aliases: ["controlnet/mlsd", "mlsd"]
    model: "@controlnet-mlsd"
  controlnet10/normal:
    aliases: ["controlnet/normal", "normal"]
    model: "@controlnet-normal"
  controlnet10/openpose:
    aliases: ["controlnet/openpose", "pose", "openpose", "pose/openpose"]
    model: "@controlnet-openpose"
    priority: 200
  controlnet10/scribble:
    aliases: ["controlnet/scribble", "sketch", "scribble"]
    priority: 50
    model: "@controlnet-scribble"
  controlnet10/seg:
    aliases: ["controlnet/seg", "segmentation", "segmentation/ade20k"]
    model: "@controlnet-seg"

- hintset_id: "hintset-sd15-controlnet11"
  controlnet11/canny:
    aliases: ["controlnet/canny", "canny"]
    model: "@controlnet11-canny"
    priority: 300
  controlnet11/depth:
    aliases: ["controlnet/depth", "depth", "depth/zoe"]
    model: "@controlnet11-depth"
    priority: 75
  controlnet11/inpaint:
    aliases: ["controlnet/inpaint", "inpaint"]
    model: "@controlnet11-inpaint"
  controlnet11/pix2pix:
    aliases: ["controlnet/pix2pix", "pix2pix"]
    model: "@controlnet11-pix2pix"
  controlnet11/lineart:
    aliases: ["controlnet/lineart", "lineart"]
    model: "@controlnet11-lineart"
  controlnet11/lineart-anime:
    aliases: ["controlnet/lineart-anime", "lineart/anime"]
    model: "@controlnet11-lineart-anime"
  controlnet11/mlsd:
    aliases: ["controlnet/mlsd", "mlsd"]
    model: "@controlnet11-mlsd"
    priority: 200
  controlnet11/normalbae:
    aliases:
      - "controlnet/normal"
      - "normal"
      - "controlnet/normalbae"
      - "normal/bae"
    model: "@controlnet11-normalbae"
    priority: 200
  controlnet11/openpose:
    aliases: ["controlnet/openpose", "pose", "openpose", "pose/openpose"]
    model: "@controlnet11-openpose"
    priority: 200
  controlnet11/scribble:
    aliases: ["controlnet/scribble", "sketch", "scribble"]
    model: "@controlnet11-scribble"
    priority: 75
  controlnet11/seg:
    aliases:
      - "controlnet/seg"
      - "segmentation"
      - "segmentation/ade20k"
      - "segmentation/coco"
    model: "@controlnet11-seg"
  controlnet11/shuffle:
    aliases: ["controlnet/shuffle", "shuffle"]
    model: "@controlnet11-shuffle"
    priority: 50
  controlnet11/softedge:
    aliases: ["controlnet/softedge", "softedge", "controlnet/hed", "hed"]
    model: "@controlnet11-softedge"
    priority: 200

- hintset_id: "hintset-sd15-common"
  "@hintset-sd15-coadapter": "*"
  "@hintset-sd15-t2i":
    - "t2i/keypose"
    - "t2i/openpose"
  "@hintset-sd15-controlnet11":
    - "controlnet11/canny"
    - "controlnet11/normalbae"
    - "controlnet11/seg"
    - "controlnet11/shuffle"
    - "controlnet11/softedge"

- hintset_id: "hintset-sd15-complete"
  "@hintset-sd15-coadapter": "*"
  "@hintset-sd15-t2i": "*"
  "@hintset-sd15-controlnet11": "*"
