---
!stable-diffusion-v2/stable-diffusion-v2-0
name: "Stable Diffusion V2.0"
description: "Stable Diffusion using the Stability V2.0 512x512 model"
source:
  model: "stabilityai/stable-diffusion-2-base"
depth_source:
  model: "stabilityai/stable-diffusion-2-depth"
inpaint_source:
  model: "stabilityai/stable-diffusion-2-inpainting"

---
!stable-diffusion-v2/stable-diffusion-v2-1
name: "Stable Diffusion V2.1"
description: "Stable Diffusion using the Stability V2.1 512x512 model"
enabled: True
source:
  model: "stabilityai/stable-diffusion-2-1-base"
depth_source:
  model: "@stable-diffusion-v2-0-depth"
inpaint_source:
  model: "@stable-diffusion-v2-0-inpaint"

---
!stable-diffusion-v2/stable-diffusion-v2-0-vpred
name: "Stable Diffusion V2.0"
description: "Stable Diffusion using the Stability V2.0 768x768 model"
source:
  model: "stabilityai/stable-diffusion-2"

---
!stable-diffusion-v2/stable-diffusion-v2-1-vpred
name: "Stable Diffusion V2.1"
description: "Stable Diffusion using the Stability V2.1 768x768 model"
source:
  model: "stabilityai/stable-diffusion-2-1"
