!stable-diffusion-v1/stable-diffusion-v1-5
name: "Stable Diffusion v1.5"
description: "Stable Diffusion using the RunwayML v1.5 model"
enabled: True
source:
  model: "runwayml/stable-diffusion-v1-5"
inpaint_source:
  model: "runwayml/stable-diffusion-inpainting"
