# This file sets some settings on various models and engines that reduces
# the amount of VRAM used for various features (in particular CLIP guidance)
# in exchange for a little quality. Generally these changes are required if
# you have < 12GB VRAM.

# Use clip-b instead of clip-h for common CLIP guidance

- model_id: "clip-common"
  model: "@laion-clip-b"

# Use miads swin2 instead of zoe for depth estimation

- id: "depth-zoe-n"
  enabled: False
  default: False

- id: "depth-midas-swin2-large-384"
  enabled: True
  default: True

---
!@template/stable-diffusion-v1
- id: "{{id}}"
  options:
    clip:
      # Don't use vae_cutouts during CLIP guidance, just approx cutouts
      # (default is 2 of each type)
      vae_cutouts: 0

---
!@template/stable-diffusion-v2
- id: "{{id}}"
  options:
    clip:
      # Don't use vae_cutouts during CLIP guidance, just approx cutouts
      # (default is 2 of each type)
      vae_cutouts: 0
