---
!@template/stable-diffusion-v2
- model_id: "{{id}}-base"
  "{{> source}}": _

- "{{#depth_source}}":
    - model_id: "{{id}}-depth"
      whitelist: ["unet", "text_encoder"]
      "{{> depth_source}}": _

- "{{#inpaint_source}}":
    - model_id: "{{id}}-inpaint"
      whitelist: ["unet", "text_encoder"]
      "{{> inpaint_source}}": _

- model_id: "{{id}}"
  model: "@{{id}}-base"
  overrides:
    "{{#depth_source}}":
      depth_unet: "@{{id}}-depth/unet"
      depth_text_encoder: "@{{id}}-depth/text_encoder"
    "{{#inpaint_source}}":
      inpaint_unet: "@{{id}}-inpaint/unet"
      inpaint_text_encoder: "@{{id}}-inpaint/text_encoder"

- id: "{{id}}"
  name: "{{name}}"
  description: "{{description}}"
  model: "@{{id}}"
  enabled: "{{enabled:False}}"
  hintset: "hintset-sd21-common"
  overrides:
    clip: "@clip-common"

---
!@stable-diffusion-v2/stable-diffusion-v2-1-finetune
- model_id: "{{id}}-base"
  whitelist:
    - "{{#has_unet:True}}":
        - "unet"
    - "{{#has_text_encoder:True}}":
        - "text_encoder"
    - "{{#has_vae:False}}":
        - "vae"

- "{{^inpaint_source}}":
    - "{{#has_unet:True}}":
        - model_id: "{{id}}-inpaint-unet"
          type: "mix"
          model:
            - "@stable-diffusion-v2-0-inpaint/unet"
            - "@{{id}}-base/unet"
          mix:
            type: "difference"
            base: "@stable-diffusion-v2-1-base/unet"
            alpha: 0

    - "{{#has_text_encoder:True}}":
        - model_id: "{{id}}-inpaint-text_encoder"
          type: "mix"
          model:
            - "@stable-diffusion-v2-1-base/text_encoder"
            - "@{{id}}-base/text_encoder"

- model_id: "{{id}}"
  model: "@stable-diffusion-v2-1"
  overrides:
    "{{#has_unet:True}}":
      unet: "@{{id}}-base/unet"
    "{{#has_text_encoder:True}}":
      text_encoder: "@{{id}}-base/text_encoder"
    "{{#has_vae:False}}":
      vae: "@{{id}}-base/vae"
    "{{^inpaint_source}}":
      "{{#has_unet:True}}":
        inpaint_unet: "@{{id}}-inpaint-unet"
      "{{#has_text_encoder:True}}":
        inpaint_text_encoder: "@{{id}}-inpaint-text_encoder"

---
!@stable-diffusion-v2-1-finetune/stable-diffusion-v2-1-ckpt
- !params
  source: "" # Remove the source for the {id}}-base model
  inpaint_source: "" # Remove the inpaint_source for the {id}}-base model

- model_id: "{{id}}-ckpt"
  type: "ckpt/v2-inference"
  whitelist:
    - "{{#has_unet:True}}":
        - "unet"
    - "{{#has_text_encoder:True}}":
        - "text_encoder"
    - "{{#has_vae:False}}":
        - "vae"
  "{{> source}}": _

- model_id: "{{id}}-base"
  fallback: "@{{id}}-ckpt"
  whitelist: !none

---
!@stable-diffusion-v2/stable-diffusion-v2-1-vpred-finetune
- model_id: "{{id}}-base"
  whitelist:
    - "{{#has_unet:True}}":
        - "unet"
    - "{{#has_text_encoder:True}}":
        - "text_encoder"
    - "{{#has_vae:False}}":
        - "vae"

- model_id: "{{id}}"
  model: "@stable-diffusion-v2-1-vpred"
  overrides:
    "{{#has_unet:True}}":
      unet: "@{{id}}-base/unet"
    "{{#has_text_encoder:True}}":
      text_encoder: "@{{id}}-base/text_encoder"
    "{{#has_vae:False}}":
      vae: "@{{id}}-base/vae"

---
!@stable-diffusion-v2-1-vpred-finetune/stable-diffusion-v2-1-vpred-ckpt
- !params
  source: "" # Remove the source for the {id}}-base model
  inpaint_source: "" # Remove the inpaint_source for the {id}}-base model

- model_id: "{{id}}-ckpt"
  type: "ckpt/v2-inference-v"
  whitelist:
    - "{{#has_unet:True}}":
        - "unet"
    - "{{#has_text_encoder:True}}":
        - "text_encoder"
    - "{{#has_vae:False}}":
        - "vae"
  "{{> source}}": _

- model_id: "{{id}}-base"
  fallback: "@{{id}}-ckpt"
  whitelist: !none
