---
!stable-diffusion-v1-5-ckpt/old-fish
name: "Old Fish"
description: "An anime-style finetune of Stable Diffusion v1.5"
has_text_encoder: False
source:
  model: "https://civitai.com/api/download/models/22052"

---
- id: "old-fish"
  overrides:
    vae: "@orange-vae/vae"
