---
!stable-diffusion-v1-5-ckpt/fish-mix
name: "Fish Mix"
description: "An anime-style finetune of Stable Diffusion v1.5"
has_text_encoder: False
vae: "@orange-vae"
source:
  model: "https://civitai.com/api/download/models/27424"

---
!stable-diffusion-v1-5-ckpt/old-fish
name: "Old Fish"
description: "An anime-style finetune of Stable Diffusion v1.5"
has_text_encoder: False
vae: "@orange-vae"
source:
  model: "https://civitai.com/api/download/models/22052"
